name: spirittrips
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^8.1.3
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  file_picker_writable: ^2.1.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  fpdart: ^1.1.0
  freezed_annotation:
  get_it: ^7.7.0
  image_picker: ^1.1.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  # l: ^4.0.2
  loader_overlay: ^4.0.0
  mobile_scanner: 4.0.1
  pinput: ^4.0.0
  provider: ^6.1.2
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.1.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  table_calendar: ^3.1.1
  talker: ^4.2.3
  talker_bloc_logger: ^4.2.3
  talker_dio_logger: ^4.2.3
  talker_flutter: ^4.2.3
  talker_logger: ^4.2.3
  timelines: ^0.1.0
  url_launcher: ^6.2.6
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_places_flutter: ^2.0.9

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.5.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  lint: ^2.3.0

flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/temp/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-Bold.ttf
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-BoldItalic.ttf
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-Demi.ttf
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-DemiItalic.ttf
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-Heavy.ttf
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-HeavyItalic.ttf
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-Italic.ttf
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-Light.ttf
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-LightItalic.ttf
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-Medium.ttf
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-MediumItalic.ttf
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-Regular.ttf
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-Thin.ttf
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-ThinItalic.ttf
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-UltraLight.ttf
        - asset: assets/fonts/Avenir-Next/AvenirNextCyr-UltraLightIt.ttf
